overwrite: true
schema: "http://localhost:10003/graphql"
documents:
  - "src/graphql/**/*.graphql"
  - "src/graphql/**/*.gql"
  - "src/**/*.ts"
  - "src/**/*.tsx"
generates:
  ./gql/:
    preset: "client"
    presetConfig: 
      fragmentMasking: false  
  ./graphql.schema.json:
    plugins:
      - "introspection"

