overwrite: true
schema: "http://localhost:10013/graphql"
documents:
  - "src/graphql/**/*.graphql"
  - "src/graphql/**/*.gql"
  - "src/**/*.ts"
  - "src/**/*.tsx"
generates:
  ./gql/:
    preset: "client"
  ./graphql.schema.json:
    plugins:
      - "introspection"
  # ./gql/types.ts:
  #   plugins:
  #     - typescript
  #     - typescript-operations
